env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - warn
    - caughtErrors: all
      caughtErrorsIgnorePattern: "^(_|unused($|[A-Z].*))$"
      argsIgnorePattern: "^(_|unused($|[A-Z].*))$"
      varsIgnorePattern: "^(_|unused($|[A-Z].*))$"
  quotes:
    - error
    - single
  semi:
    - error
    - always
